# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hood',
            name='admin',
        ),
    ]
